# This file tells cargo-about which licenses are compatible with this project's GPLv3 license.
accepted = [
  "MIT",
  "Apache-2.0",
  "ISC",
  "BSD-3-Clause",
  "BSD-2-Clause",
  "BSL-1.0",
  "Apache-2.0 WITH LLVM-exception",
  "Unicode-3.0",
  "GPL-3.0",
  "MPL-2.0",
  "Zlib",
  "OpenSSL",
]
