[package]
name = "rustache"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
icalendar = "0.17"
uuid = { version = "1.4", features = ["v4"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.9"
directories = "6.0"

# Network Stack
libdav = "0.9.6"
http = "1.3"
hyper-util = { version = "0.1", features = ["client", "client-legacy", "http1", "tokio"] }
hyper-rustls = { version = "0.27", features = ["native-tokio"] }
tower-http = { version = "0.6", features = ["auth"] }
rustls = { version = "0.23", default-features = false, features = ["std", "tls12"] }

# TUI
ratatui = "0.29"
crossterm = "0.29"
anyhow = "1.0"